#!/usr/bin/env ruby

# How many distinct terms are in the sequence generated by ab for 2  a  100
# and 2  b  100

numbers = []

(2..100).each do |a|
  (2..100).each do |b|
    numbers << a**b
  end
end

# remove duplicates
numbers.uniq!

puts "Answer: #{numbers.size}"